WebApp_Security/WebApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebApp.Data.Account;

namespace WebApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AccountController : ControllerBase
    {
        private readonly SignInManager<User> signInManager;

        public AccountController(SignInManager<User> signInManager)
        {
            this.signInManager = signInManager;
        }

        public async Task<IActionResult> ExternalLoginCallback()
        {
            var loginInfo = await signInManager.GetExternalLoginInfoAsync();
            var emailClaim = loginInfo.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email);
            var userClaim = loginInfo.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name);

            if (emailClaim != null && userClaim != null)
            {
                var user = new User { Email = emailClaim.Value, UserName = userClaim.Value };
                await signInManager.SignInAsync(user, false);                
            }

            return RedirectToPage("/Index");
        }
    }
}

WebApp_Security/WebApp/Pages/Account/AuthenticatorWithMFASetup.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QRCoder;
using WebApp.Data.Account;

namespace WebApp.Pages.Account
{
    [Authorize]
    public class AuthenticatorWithMFASetupModel : PageModel
    {
        private readonly UserManager<User> userManager;

        [BindProperty]
        public SetupMFAViewModel ViewModel { get; set; }

        [BindProperty]
        public bool Succeeded { get; set; }

        public AuthenticatorWithMFASetupModel(UserManager<User> userManager)
        {
            this.userManager = userManager;
            this.ViewModel = new SetupMFAViewModel();
            this.Succeeded = false;
        }

        public async Task OnGetAsync()
        {
            var user = await userManager.GetUserAsync(base.User);
            await userManager.ResetAuthenticatorKeyAsync(user);
            var key = await userManager.GetAuthenticatorKeyAsync(user);
            this.ViewModel.Key = key;
            this.ViewModel.QRCodeBytes = GenerateQRCodeBytes("my web app", key, user.Email);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var user = await this.userManager.GetUserAsync(base.User);
            if (await this.userManager.VerifyTwoFactorTokenAsync(
                user,
                userManager.Options.Tokens.AuthenticatorTokenProvider,
                this.ViewModel.SecurityCode))
            {
                await userManager.SetTwoFactorEnabledAsync(user, true);
                this.Succeeded = true;
            }
            else
            {
                ModelState.AddModelError("AuthenticatorSetup", "Some went wrong with authenticator setup.");                
            }

            return Page();
        }

        private Byte[] GenerateQRCodeBytes(string provider, string key, string userEmail)
        {
            var qrCodeGenerater = new QRCodeGenerator();
            var qrCodeData = qrCodeGenerater.CreateQrCode(
                $"otpauth://totp/{provider}:{userEmail}?secret={key}&issuer={provider}",
                QRCodeGenerator.ECCLevel.Q);
            var qrCode = new QRCode(qrCodeData);
            var qrCodeImage = qrCode.GetGraphic(20);

            return BitmapToByteArray(qrCodeImage);
        }

        private Byte[] BitmapToByteArray(Bitmap image)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                image.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }            
        }
    }

    public class SetupMFAViewModel
    {
        public string Key { get; set; }

        [Required]
        [Display (Name = "Code")]
        public string SecurityCode { get; set; }

        public Byte[] QRCodeBytes { get; set; }
    }

}

WebApp_Security/WebApp/Pages/Account/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Data.Account;

namespace WebApp.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<User> userManager;

        [BindProperty]
        public string Message { get; set; }

        public ConfirmEmailModel(UserManager<User> userManager)
        {
            this.userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(string userId, string token)
        {
            var user = await this.userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var result = await this.userManager.ConfirmEmailAsync(user, token);                
                if (result.Succeeded)
                {
                    this.Message = "Email address is successfully confirm, now you can try to login.";
                    return Page();
                }
            }

            this.Message = "Failed to validate email.";
            return Page();
        }
    }
}

WebApp_Security/WebApp/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Data.Account;

namespace WebApp.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<User> signInManager;

        public LoginModel(SignInManager<User> signInManager)
        {
            this.signInManager = signInManager;
        }

        [BindProperty]
        public CredentialViewModel Credential { get; set; }

        [BindProperty]
        public IEnumerable<AuthenticationScheme> ExternalLoginProviders { get; set; }

        public async Task OnGetAsync()
        {
            this.ExternalLoginProviders = await signInManager.GetExternalAuthenticationSchemesAsync();
        }  
        
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var result = await signInManager.PasswordSignInAsync(this.Credential.Email,
                this.Credential.Password,
                this.Credential.RememberMe,
                false);

            if (result.Succeeded)
            {
                return RedirectToPage("/Index");
            }
            else
            {
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("/Account/LoginTwoFactorWithAuthenticator",
                        new {                             
                            RememberMe = this.Credential.RememberMe
                        });
                }

                if (result.IsLockedOut){
                    ModelState.AddModelError("Login", "You are locked out.");
                }
                else
                {   
                    ModelState.AddModelError("Login", "Failed to login.");
                }

                return Page();
            }
        }

        public IActionResult OnPostLoginExternally(string provider)
        {
            var properties = signInManager.ConfigureExternalAuthenticationProperties(provider, null);
            properties.RedirectUri = Url.Action("ExternalLoginCallback", "Account");

            return Challenge(properties, provider);
        }
    }

    public class CredentialViewModel
    {
        [Required]        
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remeber Me")]
        public bool RememberMe { get; set; }
    }
}

WebApp_Security/WebApp/Pages/Account/LoginTwoFactor.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Data.Account;
using WebApp.Services;

namespace WebApp.Pages.Account
{    
    public class LoginTwoFactorModel : PageModel
    {
        private readonly UserManager<User> userManager;
        private readonly IEmailService emailService;
        private readonly SignInManager<User> signInManager;

        [BindProperty]
        public EmailMFA EmailMFA { get; set; }

        public LoginTwoFactorModel(
            UserManager<User> userManager, 
            IEmailService emailService,
            SignInManager<User> signInManager)
        {
            this.userManager = userManager;
            this.emailService = emailService;
            this.signInManager = signInManager;
            this.EmailMFA = new EmailMFA();
        }

        public async Task OnGetAsync(string email, bool rememberMe)
        {
            var user = await userManager.FindByEmailAsync(email);

            this.EmailMFA.SecurityCode = string.Empty;
            this.EmailMFA.RememberMe = rememberMe;

            // Generate the code
            var securityCode = await userManager.GenerateTwoFactorTokenAsync(user, "Email");

            // Send to the user
            await emailService.SendAsync("frankliu.associates@gmail.com",
                email,
                "My Web App's OTP",
                $"Please use this code as the OTP: {securityCode}");
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var result = await signInManager.TwoFactorSignInAsync("Email",
                this.EmailMFA.SecurityCode,
                this.EmailMFA.RememberMe,
                false);

            if (result.Succeeded)
            {
                return RedirectToPage("/Index");
            }
            else
            {
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Login2FA", "You are locked out.");
                }
                else
                {
                    ModelState.AddModelError("Login2FA", "Failed to login.");
                }

                return Page();
            }
        }
    }

    public class EmailMFA
    {
        [Required]
        [Display(Name = "Security Code")]
        public string SecurityCode { get; set; }
        public bool RememberMe { get; set; }
    }
}

WebApp_Security/WebApp/Pages/Account/LoginTwoFactorWithAuthenticator.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Data.Account;

namespace WebApp.Pages.Account
{
    public class LoginTwoFactorWithAuthenticatorModel : PageModel
    {
        private readonly SignInManager<User> signInManager;

        [BindProperty]
        public AuthenticatorMFA AuthenticatorMFA { get; set; }

        public LoginTwoFactorWithAuthenticatorModel(SignInManager<User> signInManager)
        {
            this.AuthenticatorMFA = new AuthenticatorMFA();
            this.signInManager = signInManager;
        }

        public void OnGet(bool rememberMe)
        {
            this.AuthenticatorMFA.SecurityCode = string.Empty;
            this.AuthenticatorMFA.RememberMe = rememberMe;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var result = await signInManager.TwoFactorAuthenticatorSignInAsync(
                this.AuthenticatorMFA.SecurityCode,
                this.AuthenticatorMFA.RememberMe,
                false);

            if (result.Succeeded)
            {
                return RedirectToPage("/Index");
            }
            else
            {
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Authenticator2FA", "You are locked out.");
                }
                else
                {
                    ModelState.AddModelError("Authenticator2FA", "Failed to login.");
                }

                return Page();
            }
        }
    }

    public class AuthenticatorMFA
    {
        [Required]
        [Display(Name = "Code")]
        public string SecurityCode { get; set; }

        public bool RememberMe { get; set; }
    }
}

WebApp_Security/WebApp/Pages/Account/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Data.Account;

namespace WebApp.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly Microsoft.AspNetCore.Identity.SignInManager<User> signInManager;

        public LogoutModel(SignInManager<User> signInManager)
        {
            this.signInManager = signInManager;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("/Account/Login");
        }
    }
}

WebApp_Security/WebApp/Pages/Account/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Data.Account;
using WebApp.Services;

namespace WebApp.Pages.Account
{
    public class RegisterModel : PageModel
    {
        private readonly UserManager<User> userManager;
        private readonly IEmailService emailService;

        public RegisterModel(UserManager<User> userManager,
            IEmailService emailService)
        {
            this.userManager = userManager;
            this.emailService = emailService;
        }

        [BindProperty]
        public RegisterViewModel RegisterViewModel { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            // Validating Email address (Optional)

            // Create the user 
            var user = new User
            {
                Email = RegisterViewModel.Email,
                UserName = RegisterViewModel.Email                
            };

            var claimDepartment = new Claim("Department", RegisterViewModel.Department);
            var claimPosition = new Claim("Position", RegisterViewModel.Position);

            var result = await this.userManager.CreateAsync(user, RegisterViewModel.Password);
            if (result.Succeeded)
            {
                await this.userManager.AddClaimAsync(user, claimDepartment);
                await this.userManager.AddClaimAsync(user, claimPosition);

                var confirmationToken = await this.userManager.GenerateEmailConfirmationTokenAsync(user);
                var confirmationLink = Url.PageLink(pageName: "/Account/ConfirmEmail",
                    values: new { userId = user.Id, token = confirmationToken });                

                await emailService.SendAsync("frankliu.associates@gmail.com",
                    user.Email,
                    "Please confirm your email",
                    $"Please click on this link to confirm your email address: {confirmationLink}");

                return RedirectToPage("/Account/Login");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("Register", error.Description);
                }

                return Page();
            }
        }
    }

    public class RegisterViewModel
    {
        [Required]
        [EmailAddress(ErrorMessage ="Invalid email address.")]
        public string Email { get; set; }

        [Required]
        [DataType(dataType:DataType.Password)]
        public string Password { get; set; }

        [Required]
        public string Department { get; set; }

        [Required]
        public string Position { get; set; }
    }
}

WebApp_Security/WebApp/Pages/Account/AuthenticatorWithMFASetup.cshtml
@page
@model WebApp.Pages.Account.AuthenticatorWithMFASetupModel
@{
}

<h3>Step 1:</h3>
<p>
    Please scan the QR Code or enter the key to your authenticator app:    
</p>
<p>
    <img src="@string.Format("data:image/png;base64,{0}", 
             @Convert.ToBase64String(Model.ViewModel.QRCodeBytes))" 
         width="300" 
         height="300"/>
</p>
<br />
<p>
    @Model.ViewModel.Key
</p>
<br />
<h3>Step 2:</h3>
<p>
    Please enter the code from your authenticator app:
</p>
<form method="post">
    @if (Model.Succeeded)
    {
        <div class="alert alert-success">
            The authenticator is successfully setup.
        </div>
    }
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="ViewModel.SecurityCode"></label>
        </div>
        <div class="col">
            <input type="text" asp-for="ViewModel.SecurityCode" class="form-control" autocomplete="off" />
        </div>
        <span class="text-danger" asp-validation-for="ViewModel.SecurityCode"></span>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <input type="submit" class="btn btn-primary" value="Verify" />
        </div>
        <div class="col"> 
            <input type="hidden" asp-for="ViewModel.Key" />
            <input type="hidden" asp-for="ViewModel.QRCodeBytes" />
        </div>
    </div>
</form>

WebApp_Security/WebApp/Pages/Account/ConfirmEmail.cshtml
@page
@model WebApp.Pages.Account.ConfirmEmailModel
@{
}

<p>
    @Model.Message
</p>

WebApp_Security/WebApp/Pages/Account/Login.cshtml
@page
@model WebApp.Pages.Account.LoginModel
@{
}

<p>
    <h3>User Login</h3>
</p>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Credential.Email"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="Credential.Email" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Credential.Email"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Credential.Password"></label>
            </div>
            <div class="col">
                <input type="password" asp-for="Credential.Password" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Credential.Password"></span>
        </div>
        <div class="row form-check mb-2">
            <div class="col-2">
                <input type="checkbox" asp-for="Credential.RememberMe" class="form-check-input" />
                <label class="form-check-label" asp-for="Credential.RememberMe"></label>
            </div>
            <div class="col">

            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Login" />
            </div>
            <div class="col">
                <a class="btn btn-link" href="/Account/Register">Sign Up</a>
            </div>
        </div>
        <br />
        <p>
            Social Media Logins:
            <div class="form-group">
                @foreach(var provider in Model.ExternalLoginProviders)
                {
                    <button type="submit"
                            asp-page-handler="LoginExternally"
                            name="provider"
                            value="@provider.Name"
                            class="btn btn-primary"
                            >
                        Login with @provider.DisplayName
                    </button>
                            
                }
            </div>
        </p>
    </form>
</div>

WebApp_Security/WebApp/Pages/Account/LoginTwoFactor.cshtml
@page
@model WebApp.Pages.Account.LoginTwoFactorModel
@{
}


<p>
    <h3>Please enter the Code from your email:</h3>
</p>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="EmailMFA.SecurityCode"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="EmailMFA.SecurityCode" class="form-control" autocomplete="off" />
            </div>
            <span class="text-danger" asp-validation-for="EmailMFA.SecurityCode"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col">
                <input type="hidden" asp-for="EmailMFA.RememberMe" />
            </div>
        </div>
    </form>
</div>

WebApp_Security/WebApp/Pages/Account/LoginTwoFactorWithAuthenticator.cshtml
@page
@model WebApp.Pages.Account.LoginTwoFactorWithAuthenticatorModel
@{
}


<p>
    <h3>Please enter the Code from your authenticator app:</h3>
</p>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="AuthenticatorMFA.SecurityCode"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="AuthenticatorMFA.SecurityCode" class="form-control" autocomplete="off" />
            </div>
            <span class="text-danger" asp-validation-for="AuthenticatorMFA.SecurityCode"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col">
                <input type="hidden" asp-for="AuthenticatorMFA.RememberMe" />
            </div>
        </div>
    </form>
</div>

WebApp_Security/WebApp/Pages/Account/Logout.cshtml
@page
@model WebApp.Pages.Account.LogoutModel
@{
}

WebApp_Security/WebApp/Pages/Account/Register.cshtml
@page
@model WebApp.Pages.Account.RegisterModel
@{
}

<p>
    <h3>User Registration</h3>
</p>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Email"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="RegisterViewModel.Email" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Email"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Password"></label>
            </div>
            <div class="col">
                <input type="password" asp-for="RegisterViewModel.Password" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Password"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Department"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="RegisterViewModel.Department" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Department"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Position"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="RegisterViewModel.Position" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Position"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Register" />
            </div>
            <div class="col">

            </div>
        </div>
    </form>
</div>

WebApp_Security/WebApp/Pages/Account/UserProfile.cshtml
@page
@model WebApp.Pages.Account.UserProfileModel
@{
}

<form method="post">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="UserProfile.Email"></label>
        </div>
        <div class="col">
            <input type="text" asp-for="UserProfile.Email" class="form-control" readonly />
        </div>
        <span class="text-danger" asp-validation-for="UserProfile.Email"></span>
    </div>    
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="UserProfile.Department"></label>
        </div>
        <div class="col">
            <input type="text" asp-for="UserProfile.Department" class="form-control" />
        </div>
        <span class="text-danger" asp-validation-for="UserProfile.Department"></span>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="UserProfile.Position"></label>
        </div>
        <div class="col">
            <input type="text" asp-for="UserProfile.Position" class="form-control" />
        </div>
        <span class="text-danger" asp-validation-for="UserProfile.Position"></span>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <input type="submit" class="btn btn-primary" value="Save" />
        </div>
        <div class="col">

        </div>
    </div>
</form>

@if (!string.IsNullOrWhiteSpace(Model.SuccessMessage) )
{
    <div class="alert alert-success" role="alert">
        @Model.SuccessMessage
    </div>
}